frontend:
  replicaCount: 1
  ingress:
    hosts:
      - host: app.dev.example.fr
        paths:
          - path: /
            pathType: Prefix
backend:
  language: fr
  replicaCount: 1
  ingress:
    hosts:
      - host: api.dev.example.fr
        paths:
          - path: /
            pathType: Prefix
