apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    path: k8s/k8s/helm
    repoURL: https://github.com/thibaultserti/formations-solutions.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values/prod.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
